// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package pea.grpc.hello



@SerialVersionUID(0L)
final case class HelloRequest(
    greeting: String = ""
    ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[HelloRequest] with com.trueaccord.lenses.Updatable[HelloRequest] {
    @transient
    private[this] var __serializedSizeCachedValue: Int = 0
    private[this] def __computeSerializedValue(): Int = {
      var __size = 0
      if (greeting != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, greeting) }
      __size
    }
    final override def serializedSize: Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): Unit = {
      {
        val __v = greeting
        if (__v != "") {
          _output__.writeString(1, __v)
        }
      };
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): pea.grpc.hello.HelloRequest = {
      var __greeting = this.greeting
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __greeting = _input__.readString()
          case tag => _input__.skipField(tag)
        }
      }
      pea.grpc.hello.HelloRequest(
          greeting = __greeting
      )
    }
    def withGreeting(__v: String): HelloRequest = copy(greeting = __v)
    def getFieldByNumber(__fieldNumber: Int): scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = greeting
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(greeting)
      }
    }
    override def toString: String = _root_.com.trueaccord.scalapb.TextFormat.printToUnicodeString(this)
    def companion = pea.grpc.hello.HelloRequest
}

object HelloRequest extends com.trueaccord.scalapb.GeneratedMessageCompanion[pea.grpc.hello.HelloRequest] {
  implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[pea.grpc.hello.HelloRequest] = this
  def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[_root_.com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): pea.grpc.hello.HelloRequest = {
    require(__fieldsMap.keys.forall(_.getContainingType() == javaDescriptor), "FieldDescriptor does not match message type.")
    val __fields = javaDescriptor.getFields
    pea.grpc.hello.HelloRequest(
      __fieldsMap.getOrElse(__fields.get(0), "").asInstanceOf[String]
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[pea.grpc.hello.HelloRequest] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      pea.grpc.hello.HelloRequest(
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = HelloProto.javaDescriptor.getMessageTypes.get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = HelloProto.scalaDescriptor.messages(0)
  def messageCompanionForFieldNumber(__number: Int): _root_.com.trueaccord.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.com.trueaccord.scalapb.GeneratedMessageCompanion[_]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: Int): _root_.com.trueaccord.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = pea.grpc.hello.HelloRequest(
  )
  implicit class HelloRequestLens[UpperPB](_l: _root_.com.trueaccord.lenses.Lens[UpperPB, pea.grpc.hello.HelloRequest]) extends _root_.com.trueaccord.lenses.ObjectLens[UpperPB, pea.grpc.hello.HelloRequest](_l) {
    def greeting: _root_.com.trueaccord.lenses.Lens[UpperPB, String] = field(_.greeting)((c_, f_) => c_.copy(greeting = f_))
  }
  final val GREETING_FIELD_NUMBER = 1
}
