// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package pea.grpc.hello

object HelloProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq.empty
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      pea.grpc.hello.HelloRequest,
      pea.grpc.hello.HelloResponse
    )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CgtoZWxsby5wcm90bxIIcGVhLmdycGMiOQoMSGVsbG9SZXF1ZXN0EikKCGdyZWV0aW5nGAEgASgJQg3iPwoSCGdyZWV0aW5nU
  ghncmVldGluZyIxCg1IZWxsb1Jlc3BvbnNlEiAKBXJlcGx5GAEgASgJQgriPwcSBXJlcGx5UgVyZXBseTJLCgxIZWxsb1NlcnZpY
  2USOwoIU2F5SGVsbG8SFi5wZWEuZ3JwYy5IZWxsb1JlcXVlc3QaFy5wZWEuZ3JwYy5IZWxsb1Jlc3BvbnNlYgZwcm90bzM="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}